name: grappus_mobile
description: Grappus Flutter Sample App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.5"

dependencies:

  auto_route: ^4.2.1
  bloc: ^8.0.3
  dartz: ^0.10.1
  dio: ^4.0.6
  # firebase_core: ^1.20.0
  # firebase_crashlytics: ^2.8.6
  # firebase_messaging: ^12.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_local_notifications: ^9.7.0
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15


dev_dependencies:
  auto_route_generator: ^4.2.1
  bloc_test: ^9.0.3
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
